# Generated by Django 4.1.3 on 2022-11-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='sugerido',
            field=models.BooleanField(default=False),
        ),
    ]
