# Generated by Django 4.1.3 on 2022-12-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_factura_lineafactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True),
        ),
    ]
