# Generated by Django 4.1.3 on 2022-12-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_factura_lineafactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteregistrado',
            name='gusta',
            field=models.ManyToManyField(blank=True, to='app.maquina'),
        ),
    ]
