# Generated by Django 4.1.3 on 2022-12-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_clienteregistrado_gusta'),
        ('app', '0008_alter_cliente_apellidos_alter_cliente_correo_and_more'),
    ]

    operations = [
    ]
